/* eslint-disable no-unused-vars */

export enum AppRoutes {
	CONDITIONS_STACK = "CONDITIONS_STACK",
	FORECAST_STACK = "FORECAST_STACK",
	SEARCH_STACK = "SEARCH_STACK"
}

export enum ConditionsRoutes {
	CURRENT_WEATHER_HOME_STACK = "CURRENT_WEATHER_HOME_STACK",
	LOCATION = "CURRENT_WEATHER_LOCATION"
}

export enum ForecastRoutes {
	FORECAST_HOME_STACK = "FORECAST_HOME_STACK",
	LOCATION = "FORECAST_LOCATION"
}

export enum SearchRoutes {
	SEARCH_HOME_STACK = "SEARCH_HOME_STACK",
	LOCATION = "SEARCH_LOCATION"
}
